---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-app-pod-sidecar-log-agent-config-map
data:
  config.toml: |
    default_api_key = "TIMBER_API_KEY"

    [[files]]
    path = "/var/log/logging-app/app.log"

---
apiVersion: v1
kind: Pod
metadata:
  name: logging-app-pod-sidecar-log-agent
spec:
  containers:
  - name: logging-app
    image: timberio/logging-app
    args: ["-file", "/var/log/logging-app/app.log"]
    volumeMounts:
    - name: logging-app-log-dir
      mountPath: /var/log/logging-app
  - name: timber-agent
    image: "timberio/agent:0.8.1"
    args: ["capture-files", "-c", "/timber/config.toml"]
    volumeMounts:
    - name: logging-app-pod-sidecar-log-agent-config-map
      mountPath: /timber
      readOnly: true
    - name: logging-app-log-dir
      mountPath: /var/log/logging-app
  volumes:
  - name: logging-app-log-dir
    emptyDir: {}
  - name: logging-app-pod-sidecar-log-agent-config-map
    configMap:
      name: logging-app-pod-sidecar-log-agent-config-map
